WINDOW_TITLE = 'Tibia 2 in Python'

WIDTH, HEIGHT = 1200, 800
HALF_WIDTH, HALF_HEIGHT = WIDTH//2, HEIGHT//2

FPS = 30
TILESIZE = 64
DEBUG = True
COLLISION_RANGE_SQUARED = (2 * TILESIZE)**2

RESOURCES_ROOT = 'data'

GLOBAL_COOLDOWN = 500
